### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Kopavel2** [fgenesis/tinypile#9]
Hello! 
First of all, thank you for the awesome code piece! :-)

But I would like to pinpoint an issue with JPS code: 
there is a memory leak because you dont call destructor for elements inside PodVec, 
but you use it for complex type with PodVec<Bucket> Buckets; (PodVec of PodVec's)
A simple fix is to add destructor to NodeMap:
"
	~NodeMap() {
		dealloc();
	}
"
Proper fix would include calling destructor for PodVec elements.

Best,
Pavel

**Comment by fgenesis** [comment]
The point of a PodVec (as the name suggests) was that elements are POD and thus don't require a dtor. And yes, using a PodVec of PodVecs is a bit of a hack but that's why i added explicit dealloc() for that one single case where it's used that way.
But you're right, i totally overlooked the automatic destruction, good catch. Thanks for pointing out.
I'll add the dtor but will otherwise leave the elements POD, without dtor.

Out of curiority, did you find this by looking at the code or using a leak checker? Because i was sure i had leak-checked the code at some point...

EDIT: Well, you have a point. I might actually add per-element dtors (as you suggested) at some point, but need to make sure that the compiler is smart enough to optimize away the loop over element dtors entirely. Getting rid of that hack would be nice indeed...

**Comment by Kopavel2** [comment]
Glad to help!
I found the leak by using default CRT leak checker (_CRTDBG_LEAK_CHECK_DF). :-)
